version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_rinha
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=user_rinha
      - POSTGRES_PASSWORD=mysecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: